### ISSUE TITLE
Volume conflict in container with openwb.conf

### ISSUE THREAD

**Issue by arturwolf** [IngmarStein/openwb-docker#3]
With the volume /var/www/html/openWB/openwb.conf there are sed conflicts in container.

Like in /var/www/html/openWB/runs/replaceinconfig.sh

sed -i "s,$1.*,$1$2,g" /var/www/html/openWB/openwb.conf

Docker prevents move of volumes, because of inode change.

So, for example,  at once charging with charge limitation does not work 
Because relevant settings in openwb.conf are not changed.

**Comment by IngmarStein** [comment]
Thanks for spotting that. This needs to be fixed upstream, so please follow along in https://github.com/snaptec/openWB/pull/1404.

**Comment by IngmarStein** [comment]
This should be fixed now and a new image version was pushed to Docker Hub. Please reopen if this is still an issue.

**Comment by arturwolf** [comment]
Why is the fix  https://github.com/snaptec/openWB/pull/1404 reverted?

**Comment by IngmarStein** [comment]
Second try at https://github.com/snaptec/openWB/pull/1415

**Comment by IngmarStein** [comment]
Closing this since the fix can't be upstreamed (see https://github.com/snaptec/openWB/pull/1415)
