### ISSUE TITLE
SoC update does not work

### ISSUE THREAD

**Issue by DFS-90** [IngmarStein/openwb-docker#5]
Hi,

is there a solution for the SoC update? 
It doesn't work in openwb-docker - I believe that it might depend on a binary which is designed for Raspberry Pi etc.

Still, my Linux skills are limited and not sufficient for compiling a binary for x86 / x64... :-D

Thanks in advance,
David

**Comment by IngmarStein** [comment]
Hi,

sorry, this project is no longer active and I'll archive the repository after closing this issue. The OpenWB team blocked upstream fixes, rendering a community-supported container solution infeasible. Thanks for your interest!
